/*
 * IMPORTANT!
 * This file has been automatically generated,
 * in order to update it's content execute "npm run update"
 */
'use strict'

module.exports = {
  rules: {
    'attribute-hyphenation': require('./rules/attribute-hyphenation'),
    'attributes-order': require('./rules/attributes-order'),
    'comment-directive': require('./rules/comment-directive'),
    'component-name-in-template-casing': require('./rules/component-name-in-template-casing'),
    'html-closing-bracket-newline': require('./rules/html-closing-bracket-newline'),
    'html-closing-bracket-spacing': require('./rules/html-closing-bracket-spacing'),
    'html-end-tags': require('./rules/html-end-tags'),
    'html-indent': require('./rules/html-indent'),
    'html-quotes': require('./rules/html-quotes'),
    'html-self-closing': require('./rules/html-self-closing'),
    'jsx-uses-vars': require('./rules/jsx-uses-vars'),
    'k-bind-style': require('./rules/k-bind-style'),
    'k-on-style': require('./rules/k-on-style'),
    'max-attributes-per-line': require('./rules/max-attributes-per-line'),
    'multiline-html-element-content-newline': require('./rules/multiline-html-element-content-newline'),
    'mustache-interpolation-spacing': require('./rules/mustache-interpolation-spacing'),
    'name-property-casing': require('./rules/name-property-casing'),
    'no-async-in-computed-properties': require('./rules/no-async-in-computed-properties'),
    'no-confusing-k-for-k-if': require('./rules/no-confusing-k-for-k-if'),
    'no-dupe-keys': require('./rules/no-dupe-keys'),
    'no-duplicate-attributes': require('./rules/no-duplicate-attributes'),
    'no-k-html': require('./rules/no-k-html'),
    'no-multi-spaces': require('./rules/no-multi-spaces'),
    'no-parsing-error': require('./rules/no-parsing-error'),
    'no-reserved-keys': require('./rules/no-reserved-keys'),
    'no-shared-component-data': require('./rules/no-shared-component-data'),
    'no-side-effects-in-computed-properties': require('./rules/no-side-effects-in-computed-properties'),
    'no-spaces-around-equal-signs-in-attribute': require('./rules/no-spaces-around-equal-signs-in-attribute'),
    'no-template-key': require('./rules/no-template-key'),
    'no-template-shadow': require('./rules/no-template-shadow'),
    'no-textarea-mustache': require('./rules/no-textarea-mustache'),
    'no-unused-components': require('./rules/no-unused-components'),
    'no-unused-vars': require('./rules/no-unused-vars'),
    'no-use-k-if-with-k-for': require('./rules/no-use-k-if-with-k-for'),
    'order-in-components': require('./rules/order-in-components'),
    'prop-name-casing': require('./rules/prop-name-casing'),
    'require-component-is': require('./rules/require-component-is'),
    'require-default-prop': require('./rules/require-default-prop'),
    'require-k-for-key': require('./rules/require-k-for-key'),
    'require-prop-type-constructor': require('./rules/require-prop-type-constructor'),
    'require-prop-types': require('./rules/require-prop-types'),
    'require-render-return': require('./rules/require-render-return'),
    'require-valid-default-prop': require('./rules/require-valid-default-prop'),
    'return-in-computed-property': require('./rules/return-in-computed-property'),
    'script-indent': require('./rules/script-indent'),
    'singleline-html-element-content-newline': require('./rules/singleline-html-element-content-newline'),
    'this-in-template': require('./rules/this-in-template'),
    'use-k-on-exact': require('./rules/use-k-on-exact'),
    'valid-k-bind': require('./rules/valid-k-bind'),
    'valid-k-cloak': require('./rules/valid-k-cloak'),
    'valid-k-else-if': require('./rules/valid-k-else-if'),
    'valid-k-else': require('./rules/valid-k-else'),
    'valid-k-for': require('./rules/valid-k-for'),
    'valid-k-html': require('./rules/valid-k-html'),
    'valid-k-if': require('./rules/valid-k-if'),
    'valid-k-model': require('./rules/valid-k-model'),
    'valid-k-on': require('./rules/valid-k-on'),
    'valid-k-once': require('./rules/valid-k-once'),
    'valid-k-pre': require('./rules/valid-k-pre'),
    'valid-k-show': require('./rules/valid-k-show'),
    'valid-k-text': require('./rules/valid-k-text'),
    'valid-template-root': require('./rules/valid-template-root')
  },
  configs: {
    'base': require('./configs/base'),
    'essential': require('./configs/essential'),
    'strongly-recommended': require('./configs/strongly-recommended'),
    'recommended': require('./configs/recommended')
  },
  processors: {
    '.kdu': require('./processor')
  }
}
