/*
* IMPORTANT!
* This file has been automatically generated,
* in order to update it's content execute "npm run update"
*/
module.exports = {
  "kdu/attribute-hyphenation": "error",
  "kdu/html-end-tags": "error",
  "kdu/html-indent": "error",
  "kdu/html-quotes": "error",
  "kdu/html-self-closing": "error",
  "kdu/jsx-uses-vars": "error",
  "kdu/max-attributes-per-line": "error",
  "kdu/mustache-interpolation-spacing": "error",
  "kdu/name-property-casing": "error",
  "kdu/no-async-in-computed-properties": "error",
  "kdu/no-confusing-k-for-k-if": "error",
  "kdu/no-dupe-keys": "error",
  "kdu/no-duplicate-attributes": "error",
  "kdu/no-multi-spaces": "error",
  "kdu/no-parsing-error": "error",
  "kdu/no-reserved-keys": "error",
  "kdu/no-shared-component-data": "error",
  "kdu/no-side-effects-in-computed-properties": "error",
  "kdu/no-template-key": "error",
  "kdu/no-textarea-mustache": "error",
  "kdu/no-unused-vars": "error",
  "kdu/order-in-components": "error",
  "kdu/require-component-is": "error",
  "kdu/require-default-prop": "error",
  "kdu/require-prop-types": "error",
  "kdu/require-render-return": "error",
  "kdu/require-k-for-key": "error",
  "kdu/require-valid-default-prop": "error",
  "kdu/return-in-computed-property": "error",
  "kdu/this-in-template": "error",
  "kdu/k-bind-style": "error",
  "kdu/k-on-style": "error",
  "kdu/valid-template-root": "error",
  "kdu/valid-k-bind": "error",
  "kdu/valid-k-cloak": "error",
  "kdu/valid-k-else-if": "error",
  "kdu/valid-k-else": "error",
  "kdu/valid-k-for": "error",
  "kdu/valid-k-html": "error",
  "kdu/valid-k-if": "error",
  "kdu/valid-k-model": "error",
  "kdu/valid-k-on": "error",
  "kdu/valid-k-once": "error",
  "kdu/valid-k-pre": "error",
  "kdu/valid-k-show": "error",
  "kdu/valid-k-text": "error"
}
